version: "3.9"

services:
  web-chat-react:
    build: .
    ports:
      - "80"
    networks:
      frontend:
        ipv4_address: 172.1.0.254
    deploy:
      replicas: 1

  cloudflared:
    image: cloudflare/cloudflared:latest
    restart: unless-stopped
    environment:
      - TUNNEL_TOKEN=${CLOUDFLARE_TOKEN}
    command: tunnel --no-autoupdate run
    networks:
      frontend:


networks:
  frontend:
    ipam:
      config:
        - subnet: 172.1.0.0/24
